---
title: "Untitled"
author: "Lucía Almorox Antón"
date: "2023-02-08"
output: html_document
---

Con este script se repite el preprocesamiento para la clasificación ADENO y SQUAMOUS pero incluyendo las muestras adenoescamosas (son solo dos y tras la eliminación de outliers, una).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(KnowSeq)
rm(list = ls())
memory.limit(size=10000)
set.seed(111)
```

Definición de las clases de interés:

```{r}
samples <- read.table(file = 'SAMPLES_CERVIX.tsv', sep = '\t', header = TRUE)
Class <- samples$Sample.Type
Class[Class=='Solid Tissue Normal'] <- 'HEALTHY'
table(Class)

library(readr)
clinical <- read_delim(file = 'clinical.tsv')

for (i in 1:nrow(samples)){
  if (Class[i] != 'HEALTHY'){
    CASE_ID_i <- samples$Case.ID[i]
    clinical_i <- clinical[clinical$case_submitter_id==CASE_ID_i,]
    ENF <- clinical_i$primary_diagnosis[1]
    Class[i] <- ENF
  }
}

table(Class)
Class[Class=='Adenocarcinoma, endocervical type'|Class=='Adenocarcinoma, NOS'|Class=='Endometrioid adenocarcinoma, NOS'] <- 'ADENO'
Class[Class=='Adenosquamous carcinoma'] <- 'ADENO_SQUAMOUS'
Class[Class != 'ADENO_SQUAMOUS' & Class != 'ADENO' & Class !='HEALTHY'] <- 'SQUAMOUS'

table(Class)
```


```{r}
# Creamos las variables necesarias
Run <- paste(samples$File.Name,".counts",sep = "")
Path <- paste("./",samples$File.ID,sep = "")
# Exportamos DataFrame a CSV
data.info2 <- data.frame(Run = Run, Path = Path, Class = Class)
#write.csv(file = "data_info_STAGES.csv", x = data.info)
```

```{r}
data.info2 <- data.info2[!(data.info2$Class=='HEALTHY'),] # solo se eliminan las muestras sanas

table(data.info2$Class)
write.csv(file = "data_info2.csv", x = data.info2)
```

Creación de la matriz corregida:

```{r}

# Cargamos y aunamos los ficheros count (tenemos los genes en filas y las 
# muestras en columnas).
countsInfo2 <- countsToMatrix("data_info2.csv", extension = "")

# Exportamos tanto la matriz de datos como los labels a nuevas variables
countsMatrix2 <- countsInfo2$countsMatrix
labels2 <- countsInfo2$labels

# Consultamos los Gene Symbols y el GC content de cada gen
# (si el valor de GC es muy grande es indicativo de que la secuenciación no
# ha ido bien, pero no vamos a prestarle atención en este caso).
myAnnotation2 <- getGenesAnnotation(rownames(countsMatrix2))

# Calculamos los valores de expresión usando la matriz de count y la anotación 
# previamente adquirida
geneExprMatrix2 <- calculateGeneExpressionValues(countsMatrix2, annotation = myAnnotation2)
# Se está haciendo ya una primera normalización aunque no es la normalización completa. 
# (los valores de conteo no son "raw" ya).
#save(geneExprMatrix2,file="geneEMAT2.RData")


# Nos quedamos solo con los genes que tienen nombre, o sea, aquellos que se 
# conocen.
geneExprMatrix2 <- geneExprMatrix2[!is.na(rownames(geneExprMatrix2)),]
# Realizamos el analisis de calidad de RNAseq: eliminamos aquellas muestras 
# que puede que tengan peor calidad o cuya distribucion de expresión se
# aleje mucho de la distribución del resto de muestras (outliers).
# Si ha eliminado alguna muestra el número de columnas se verá reducido.
QAResults2 <- RNAseqQA(geneExprMatrix2, toRemoval = TRUE, toPNG=FALSE, toPDF=FALSE)

qualityMatrix2 <- QAResults2$matrix

# Actualizamos el objeto Labels para quedarnos solo con las que corresponden
# a las muestras que han quedado tras la eliminación de outliers.
qualityLabels2 <- labels2[-which(colnames(geneExprMatrix2) %in% QAResults2$outliers)]

table(qualityLabels2) #Vemos el número de meustras que ha quitado de cada clase.

# Creamos el modelo SVA de variables subrogadas para tratar el efecto batch
  # Observamos la gráfica antes de eliminar el efecto batch
#dataPlot(qualityMatrix, qualityLabels, mode = "orderedBoxplot")
batchMatrix2 <- batchEffectRemoval(qualityMatrix2, qualityLabels2, method = "sva")
 # Observamos la gráfica después de eliminar el efecto batch
#dataPlot(batchMatrix, qualityLabels, mode = "orderedBoxplot")
save(batchMatrix2,file="MATRIZ_LIMPIA_MIXTA.RData")
save(qualityLabels2,file="quality_labels_MIXTA.RData")

```

Extraemos los datos de expresión de la muestra mixta y los guardamos.

```{r}

which(qualityLabels2=="ADENO_SQUAMOUS")
AS <- batchMatrix2[,261]
save(AS,file="ADENO_SQUAMOUS_SAMPLE.RData")
```